### ISSUE TITLE
Swagger is broken

### ISSUE THREAD

**Issue by khvn26** [SolidStateGroup/bullet-train-api#2256]
**Describe the bug**

> SwaggerGenerationError
> your query_serializer contains fields that conflict with the filter_backend or paginator_class on the view - GET /api/v1/audit/

It's likely the type mismatch between filter params and the DRF serializer:

Filter: 

```js
{
  description: '', 
  in: 'query', 
  name: 'is_system_event', 
  required: False, 
  > type: 'string' <
}, 
```

Serializer field:

```js
{
  in: 'query', 
  name: 'is_system_event', 
  required: False, 
  > type: 'boolean' <
}, 
```

The error is currently only reproducible for user id 14119.

Potentially related issue: https://github.com/axnsan12/drf-yasg/issues/514

**To Reproduce**

0. Login as user 14119.
1. Go to https://api.flagsmith.com/api/v1/docs/?format=openapi
2. Observe the HTTP 500 response.

**Expected behavior**

The server should render the OpenAPI schema.

A unit test should catch Swagger generation errors. 

**How are you running Flagsmith?**

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [x] SaaS at flagsmith.com
- [ ] Some other way

**Comment by matthewelwell** [comment]
I have looked into this a bit further - I don't believe it is related to the error provided in the description since that was fixed here: https://github.com/Flagsmith/flagsmith/pull/2326. 

It seems to only happen when users are logged in as a user that also has access to the django admin in the same browser session that they access the API docs.

**Comment by khvn26** [comment]
The issue is still reproducible in prod. Tried logging out and in again to no avail.

**Comment by matthewelwell** [comment]
Sorry, yes - it's still reproducible for sure, but I'm not convinced it's related to the exception in the description. It's definitely related to being logged in as a staff user though.
