### ISSUE TITLE
Type projectID as number in web components

### ISSUE THREAD

**Issue by Zaimwa9** [SolidStateGroup/bullet-train-api#5667]
### How are you running Flagsmith

- [x] Self Hosted with Docker
- [x] Self Hosted with Kubernetes
- [x] SaaS at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

ProjectIDs were wrongly typed as string while it is supposed to be a number type

### Steps To Reproduce

N/A

### Expected behavior

The type definitions should treat the projectID as a number and only converts to string if needed

**Comment by matthewelwell** [comment]
@Zaimwa9 @talissoncosta I have a feeling this might have been resolved in a recent(ish) change?

**Comment by talissoncosta** [comment]
Partially, we have done a great progress on it, but we still have some occurrences. A quick report below:

<img width="799" height="522" alt="Image" src="https://github.com/user-attachments/assets/efe26338-15a4-4c66-b7c6-1d374e846284" />
